version: '3.8'
services:

  oathkeeper:
    container_name: oathkeeper
    build:
      context: ../
      dockerfile: ./packages/iap-oathkeeper/Dockerfile.dev
    ports:
      - "8083:8083" # reverse proxy port configured in .oathkeeper.yaml
      - "4456:4456" # oathkeeper rest api (does not need to be open for reverse proxy to work) http://localhost:4456/rules
      - "9000:9000" # Prometheus scraping endpoint (does not need to be open for reverse proxy to work)
    depends_on:
      - frontend
      - backend


  frontend:
    container_name: frontend
    build:
      context: ../
      dockerfile: ./packages/frontend/Dockerfile.dev
    volumes:
      # Anonymous volumes to prevent connection to windows node_modules folder (aka: bookmark volumes)
      - /usr/app/node_modules
      - /usr/app/packages/frontend/node_modules
      # host volume
      - ../packages/frontend:/usr/app/packages/frontend


  backend:
    container_name: backend
    build:
      context: ../
      dockerfile: ./packages/backend/Dockerfile.dev
    volumes:
      # Anonymous volumes to prevent connection to windows node_modules folder (aka: bookmark volumes)
      - /usr/app/node_modules
      - /usr/app/packages/backend/node_modules
      # host volume
      - ../packages/backend:/usr/app/packages/backend
    environment:
      - NODE_ENV=development


  consent:
    environment:
      - HYDRA_ADMIN_URL=http://hydra:4445
    image: oryd/hydra-login-consent-node:v1.9.0
      # https://hub.docker.com/r/oryd/hydra-login-consent-node
      # https://github.com/ory/hydra-login-consent-node
    ports:
      - "3000:3000"
    restart: unless-stopped
    # networks:
    #   - intranet


  hydra:
    image: oryd/hydra:v1.9.0-sqlite
    ports:
      - "4444:4444" # Public port
      - "4445:4445" # Admin port
      - "5555:5555" # Port for hydra token user
    environment:
      - DSN=sqlite:///var/lib/sqlite/db.sqlite?_fk=true
    command:
      serve -c /etc/config/hydra/hydra.yml all --dangerous-force-http
    volumes:
      - ../packages/oidc-provider-hydra/sqlite:/var/lib/sqlite
      # -
      #   type: volume
      #   source: hydra-sqlite
      #   # source: ./packages/oidc-provider-hydra/sqlite
      #   target: /var/lib/sqlite
      #   read_only: false
      -
        type: bind
        source: ../packages/oidc-provider-hydra/config
        target: /etc/config/hydra
    restart: unless-stopped
    depends_on:
      - hydra-migrate
    # networks:
    #   - intranet

  hydra-migrate:
    image: oryd/hydra:v1.9.0-sqlite
    environment:
      - DSN=sqlite:///var/lib/sqlite/db.sqlite?_fk=true
    command:
      migrate -c /etc/config/hydra/hydra.yml sql -e --yes
    volumes:
      - ../packages/oidc-provider-hydra/sqlite:/var/lib/sqlite
      # -
      #   type: volume
      #   source: hydra-sqlite
      #   # source: ./packages/oidc-provider-hydra/sqlite
      #   target: /var/lib/sqlite
      #   read_only: false
      -
        type: bind
        source: ../packages/oidc-provider-hydra/config
        target: /etc/config/hydra
    restart: on-failure
    # networks:
    #   - intranet

# volumes:
#   hydra-sqlite:
